import type { Metadata } from 'next'
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter'
import { ThemeProvider } from '@mui/material/styles'
import { QueryProvider } from '@/components/atoms/ProviderWrapper'
import theme from '@/components/atoms/Theme'
import AdminLayout from '@/components/templates/AdminLayout'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
export default function RootLayoutAdmin({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <AppRouterCacheProvider>
      <ThemeProvider theme={theme}>
        <QueryProvider>
          <AdminLayout>{children}</AdminLayout>
        </QueryProvider>
      </ThemeProvider>
    </AppRouterCacheProvider>
  )
}
